name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Copy standalone output
        run: |
          cp -r .next/standalone ./deploy
          cp -r .next/static ./deploy/.next/static
          cp -r public ./deploy/public

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2B163D933445419AA2FDFA9A0D2C6038 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_284C1272EFDF4CB89E188D5F2AFFD490 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DBBE0ED4953944A89600158E780DA1EA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gaston-caspar'
          slot-name: 'Production'
          package: .
